### ISSUE TITLE
Update according to changed pmpcfg WARL behavior

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40s#165]
The pmpcfg.X, pmpcfg.W and pmpcfg.R  bits shall be treated as a collective WARL (0x0, 0x1, 0x3, 0x4, 0x5, 0x7) bitfield when mseccfg.MML = 0 and upon writing an illegal value the value of the combined XWR bitfield shall remain unchanged

**Comment by silabs-oivind** [comment]
This is fixed in https://github.com/openhwgroup/cv32e40s/pull/290
