### ISSUE TITLE
Wrong D-mode priv lvl

### ISSUE THREAD

**Issue by silabs-robin** [openhwgroup/cv32e40s#196]
### Component
**Component:RTL**: For issues in the RTL (e.g. for files in the rtl directory)

### Steps to Reproduce
40s hash `fdbba032`.

Trace with CEX:
![image](https://user-images.githubusercontent.com/75431602/168253374-551d9311-fbfd-4d59-80f4-4c49d05ce008.png)
This trace is long, but the color-highlights (RGB tresis) show the problem at cycle 22 (the lines below are very useful too, at cycles 15-17).
The core executes in debug mode, while the privilege mode is U-mode, and this is not allowed.

Debug spec:
![image](https://user-images.githubusercontent.com/75431602/168253996-528d4151-9325-4fca-8de9-3b0d257d50b1.png)

Reproduction:
```
cover -name mycov_dmodeumode {
  ((dut_wrap.cv32e40s_wrapper_i.rvfi_i.rvfi_valid == 1'b1)
  && (dut_wrap.cv32e40s_wrapper_i.rvfi_i.rvfi_dbg_mode == 1'b1)
  && (dut_wrap.cv32e40s_wrapper_i.rvfi_i.rvfi_mode == PRIV_LVL_U))
};
```
This cover should be an ok starting point.

**Comment by silabs-robin** [comment]
@Silabs-ArjanB @silabs-oysteink

**Comment by Silabs-ArjanB** [comment]
@silabs-oysteink Is all code execution in debug mode 'due to abstract commands'? Note that section A.2 of the debug spec states "This implementation only implements the Access Register abstract command for GPRs on a halted
hart, and relies on the Program Buffer for all other operations."

**Comment by Silabs-ArjanB** [comment]
@silabs-robin I filed https://github.com/riscv/riscv-debug-spec/issues/744 to get a better understanding about what is really the requirement here.

**Comment by Silabs-ArjanB** [comment]
Should be fixed with https://github.com/openhwgroup/cv32e40s/pull/268

**Comment by silabs-robin** [comment]
The issue has been fixed.
I have an assertion ("a_dmode_mmode") which fails before applying the fixes, and passes after applying the fixes.

(All possible core configurations have _not_ been tested, but they will be when my assertions are merged into core-v-verif and regressions are ran.)
