### ISSUE TITLE
Bug in the MSTATUS register

### ISSUE THREAD

**Issue by silabs-anvesten** [openhwgroup/cv32e40s#243]
Attempts to write illegal value S-mode to the mpp-field in the mstatus csr. Read value should be previous legal value (U-mode), but returns M-mode.
 
### Steps to Reproduce
- checkout my branch https://github.com/silabs-anvesten/core-v-verif/tree/UsermodeTest
- cd /work/user/core-v-verif/cv32e40s/sim/uvmt
- make test TEST=privilege_tests CFG=pmp

## Environment
tested on the following cv32e40s hash: 1da7c4097158094915073c7a89be5fb48549f907

**Comment by Silabs-ArjanB** [comment]
This should be fixed with https://github.com/openhwgroup/cv32e40s/pull/247/. @silabs-anvesten could you please check if it works now on the latest RTL?

**Comment by silabs-anvesten** [comment]
Yes it does, tests clear now
