### ISSUE TITLE
Fix PMPADDR hookup to RVFI (and check/fix other similar issues if existing)

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40s#255]
For PMPADDR there is sometimes a difference in the value stored in the CSR and the value read from the CSR (as per the PMP spec). A new signal pmp_addr_n_r was introduced in the RTL to represent the 'next read value upon a write', see https://github.com/openhwgroup/cv32e40s/pull/254.

This signal is currently assigned to 0 and should be implemented (logic similar to the logic present on pmp_addr_rdata).

Similar _n_r values should be introduced for any other CSR where the value read can differ from the value actually stored.

**Comment by silabs-oivind** [comment]
Other CSRs identified that require special handling are: mscratchcsw, mscratchcswl, mnxti. These are already updated wrt RVFI. As far as I can see, no other updates are needed, and this ticket can be closed.
