### ISSUE TITLE
Update achk/rchk signals according to https://github.com/openhwgroup/cv32e40s/pull/264

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40s#265]
Update achk/rchk signals according to https://github.com/openhwgroup/cv32e40s/pull/264

**Comment by Silabs-ArjanB** [comment]
@silabs-oysteink Has this been fixed (according to mentioned PR possibly superseeded by most recent user manual if there were later changes)?

**Comment by silabs-oysteink** [comment]
Yes, this should be all ok.
