### ISSUE TITLE
MPRV not cleared when core changes from debug to user mode. 

### ISSUE THREAD

**Issue by silabs-anvesten** [openhwgroup/cv32e40s#277]
### Component
**Component:RTL**

Comment:
mstatus.MPRV bit should be cleared when exiting debug mode into user mode, this is not the case. Simulation must also be run without ISS as there is currently a mismatch error when writing changes to the dcsr.prv bit. 

### Steps to Reproduce
git hash: 
     c8ed2efc63ad8f31cf90603f19fcd35c1dd45247
git branch to look into: 
     https://github.com/silabs-anvesten/core-v-verif/tree/DebugBug
make command: 
    make test TEST=debug_priv_test CFG=pmp USE_ISS=NO

![debug mode MPRV bug](https://user-images.githubusercontent.com/107674166/183658365-d6148baf-8119-40a4-a34b-328175156b82.png)

**Comment by Silabs-ArjanB** [comment]
@silabs-anvesten This should be fixed now; please close if agreed/confirmed.
