### ISSUE TITLE
Documentation for E40S

### ISSUE THREAD

**Issue by eroom1966** [openhwgroup/cv32e40s#28]
Can I ask where is the correct reference for the E40S documentation
I have found 2 locations - maybe these are in fact equivalent ?

https://docs.openhwgroup.org/projects/cv32e40s-user-manual/
https://cv32e40s-user-manual.readthedocs.io/en/latest/

Thx
Lee

**Comment by Silabs-ArjanB** [comment]
Hi Lee,

These are the same. We normally point only to https://cv32e40s-user-manual.readthedocs.io/en/latest/ though.

**Comment by eroom1966** [comment]
thanks
