### ISSUE TITLE
Does CV32E40S support User Mode ?

### ISSUE THREAD

**Issue by eroom1966** [openhwgroup/cv32e40s#29]
@Silabs-ArjanB 
I am confused by the documentation regarding support of user mode

https://cv32e40s-user-manual.readthedocs.io/en/latest/control_status_registers.html#csr-map

for the MISA[U] bit it says the following
<html><body>

20 | RO   (0x0) | U (User mode implemented).
-- | -- | --

</body>
</html>

this indicates it is not supported.

In the document indicating support requirements of the ISS for E40S, it says the following
R-2: (CV32E40S) Support is ...
R-2.1: User mode support is at PRIORITY 3.

These are conflicting requirements.
running the E40S RTL today, MISA returns a value indicating that MISA[U]=0

Thx
Lee

**Comment by Silabs-ArjanB** [comment]
Hi @eroom1966 , the CV32E40S will unconditionally support user mode. The documentation has not fully been updated to reflect that. I fixed the misa.u bit now with https://github.com/openhwgroup/cv32e40s/pull/30.

User mode has not been implemented in the CV32E40S RTL yet (but it will), but it is okay if you add it already in the ISS for the CV32E40S.

Best regards,
Arjan

**Comment by eroom1966** [comment]
thanks
