### ISSUE TITLE
mstatus/mcause.mpp and mpie mirroring not correctly reported on rvfi

### ISSUE THREAD

**Issue by silabs-hfegran** [openhwgroup/cv32e40s#334]
## mstatus/mcause.mpp and mpie mirroring not correctly reported on rvfi

Writes to mcause.mpp/mpie is not reported on mcause rvfi_csr_wdata

### Component
RTL and/or RVFI

### Steps to Reproduce
1. [git hash](https://github.com/silabs-hfegran/core-v-verif/tree/dev_hf_40s_initial_clic_test)
2. make test TEST=clic CFG=clic_default USE_ISS=1
3. Wave dump:
![image](https://user-images.githubusercontent.com/75469886/201097481-ac226ab4-730f-4a1f-b8ba-9a774eed1031.png)

**Comment by silabs-oysteink** [comment]
This should now be fixed with the merge from cv32e40x in PR #367

**Comment by Silabs-ArjanB** [comment]
@silabs-hfegran Can you please close this if it has been fixed?
