### ISSUE TITLE
Fix mprven bit in DCSR

### ISSUE THREAD

**Issue by silabs-halfdan** [openhwgroup/cv32e40s#343]
The **mprven** bit is [documented ](https://cv32e40s-user-manual.readthedocs.io/en/latest/control_status_registers.html#debug-control-and-status-dcsr) as hardwired to 1 while it is hardwired to 0 in the RTL.

**Comment by silabs-halfdan** [comment]
Also the **stopcount** bit in the same register is seems to not be implemented

**Comment by Silabs-ArjanB** [comment]
Should be fixed once merged from 40X to 40S.

**Comment by silabs-oivind** [comment]
@Silabs-ArjanB this is merged to E40S, ticket can be closed.

**Comment by Silabs-ArjanB** [comment]
@silabs-halfdan Please close this issue if you agree it has been solved.

**Comment by silabs-halfdan** [comment]
This issue is solved, closing ticket. Also creating new ticket for ISS mismatch for the DCSR cause field.
