### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by silabs-robin** [openhwgroup/cv32e40s#362]
### Component
**Component:Doc **: For issues in the Documentation (e.g. for User Manual or README.md files)

### Problem

`mseccfg.useed`, should be bit 8, not 2.

![image](https://user-images.githubusercontent.com/75431602/208407775-6e67348c-0a12-4a2d-8fba-cdd123981782.png)

![image](https://user-images.githubusercontent.com/75431602/208407973-0ce7d0e8-2e9c-4740-bd4c-ad62f4a57a00.png)

**Comment by Silabs-ArjanB** [comment]
@silabs-robin This should be fixed now

**Comment by silabs-robin** [comment]
Is fixed.
