### ISSUE TITLE
"tdata2" WARL

### ISSUE THREAD

**Issue by silabs-robin** [openhwgroup/cv32e40s#363]
### Component
**Component:Doc **: For issues in the Documentation (e.g. for User Manual or README.md files)

### Problem

`tdata2.DATA` is specified as RW, but it is actually WARL.

https://docs.openhwgroup.org/projects/cv32e40s-user-manual/en/latest/control_status_registers.html#trigger-data-register-2-tdata2

**Comment by silabs-robin** [comment]
WARL behavior:
* Is only writable from D-mode.
    * (M-mode writes can _write any_ but are ignored.)
* With `tdata1` in mode 5 (`etrigger`), then `tdata2`'s values are limited according to exception codes.

**Comment by Silabs-ArjanB** [comment]
@silabs-robin This should be fixed now
