### ISSUE TITLE
Debug reqest without debug entry during WFI

### ISSUE THREAD

**Issue by silabs-halfdan** [openhwgroup/cv32e40s#365]
### Behavior of debug request during WFI differs from spec

If the core receives a single cycle debug request while in a WFI, the core will wake up and continue execution without entering debug mode. Entering debug mode when woken up by a debug request is required in the debug spec (4.3):

>**4.3 Wait for Interrupt Instruction**
>If halt is requested while wfi is executing, then the hart must leave the stalled state, completing
>this instruction’s execution, and then enter Debug Mode.

**Comment by Silabs-ArjanB** [comment]
Should be fixed after merge of https://github.com/openhwgroup/cv32e40x/pull/749 to 40S
