### ISSUE TITLE
Make PMP and PMA region modeling consistent

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40s#39]
https://github.com/openhwgroup/cv32e40s/pull/38 was performed to work around a DSIM crash. If this work-around works, make PMP and PMA region modeling consistent again (RTL fix likely to be done on 40X first and then merged).

**Comment by Silabs-ArjanB** [comment]
Hi @silabs-oivind, has this issue already been resolved?

**Comment by silabs-oivind** [comment]
Hi @Silabs-ArjanB. Yes, it has been resolved.
