### ISSUE TITLE
dpc bit 0 writeable in UM 0.8.0

### ISSUE THREAD

**Issue by silabs-hfegran** [openhwgroup/cv32e40s#407]
## dpc bit 0 writable in UM
User manual v0.8.0 states that bit 0 of dpc is writable
![image](https://user-images.githubusercontent.com/75469886/218099791-02e420e7-cfa3-42f8-b0fd-58de915623c9.png)

This is a violation of debug spec 4.2.8, as we do not support byte aligned instructions, and should match the writability of mepc low bits.
![image](https://user-images.githubusercontent.com/75469886/218099698-c95672c8-0851-4709-b18b-b97bf083c0d7.png)

As a consequence, writability of this bit is incorrect in the reference model which models dcsr as specified in our user manual.

**Comment by Silabs-ArjanB** [comment]
Should be fixed with https://github.com/openhwgroup/cv32e40x/pull/779 (still requires merge to 40S)
