### ISSUE TITLE
RVFI misrepresents OBI transactions?

### ISSUE THREAD

**Issue by silabs-robin** [openhwgroup/cv32e40s#410]
### Component
**Component:Other**: For any other issues

### Steps to Reproduce
1. Cvverif hash `f7f2d5`
2. My fork https://github.com/silabs-robin/core-v-verif
3. tcf_cvverif
4. a_obi_vs_rvfi

If I there is nothing I have overlooked, it seems like `rvfi_mem_*` reports memory writes that didn't happen.
In the example below it seems like there is an MPU error, so the bus access is denied, but RVFI says the mem got updated.

![image](https://user-images.githubusercontent.com/75431602/221557571-55aa74ba-68b8-430b-8c27-0d26d470fcb6.png)

**Comment by Silabs-ArjanB** [comment]
It looks like an RVFI bug indeed (it ignores the related valid signal and acts as if a memory write actually happened).

@silabs-robin I would assume that rvfi_trap.trap gets asserted as well, right?

**Comment by silabs-robin** [comment]
> I would assume that rvfi_trap.trap gets asserted as well, right?

Yes.

![image](https://user-images.githubusercontent.com/75431602/221575255-dec2b205-6712-435b-b79d-217371486326.png)

**Comment by Silabs-ArjanB** [comment]
Should be fixed by https://github.com/openhwgroup/cv32e40x/pull/816 (once merged from 40X to 40S)

**Comment by silabs-robin** [comment]
I am seeing a bound of more than double where the original CEX was found, and we have reports of a bound of "26 cycles / 12k seconds ".
Therefore, I consider the problem fixed.

_(If there exists any further problem on deeper depths then I will create a new issue for that separately.)_
