### ISSUE TITLE
Mismatch between reference manual/RTL and ISS for tdata2 (for tdata1.type==5)

### ISSUE THREAD

**Issue by silabs-halfdan** [openhwgroup/cv32e40s#412]
# Mismatch between RTL/reference manual and the ISS

In the [reference manual](https://cv32e40s-user-manual.readthedocs.io/en/latest/control_status_registers.html#trigger-data-register-2-tdata2-view-when-tdata1-type-is-0x5) the tdata2 register (for tdata1.type==5) is described with only the bits for valid exception codes as writable. In the ISS however, any value can be written.
This triggers ISS mismatches when writing these bits as the ISS will store the info in the WARL(0x0) bit fields.

**Comment by Silabs-ArjanB** [comment]
Hi @silabs-halfdan I think that the RTL and reference manual match for tdata2 with tdata1.type == 5, see https://cv32e40s-user-manual.readthedocs.io/en/latest/control_status_registers.html#trigger-data-register-2-tdata2-view-when-tdata1-type-is-0x5. The tdata2 register is not described as 32 bits of RW data as you imply above.

Should this issue therefore be rephrase to 'mismatch between ISS and reference manual / RTL'?

**Comment by silabs-halfdan** [comment]
@Silabs-ArjanB, yes I looked at the register description for the wrong tdata1.type... I will update the title and description.

**Comment by silabs-halfdan** [comment]
I will close the issue here, and open one on core-v-verif.
