### ISSUE TITLE
Signal debug_pc_o shows pointer address with clic and mret

### ISSUE THREAD

**Issue by silabs-mateilga** [openhwgroup/cv32e40s#415]
**Component:RTL**

When a mret instruction restarts a clic pointer fetch, the expected value for debug_pc_o is the address of the mret instruction, but it actually reports the address of the pointer. See pipeline vizualisation in the attached image.

Reproduce by formally proving assert a_debug_pc_o_inv in the debug_asserts assertion set, with clic enabled.

![image](https://user-images.githubusercontent.com/59358563/224267384-dd343009-e632-4b4f-a1f6-44b934c7945c.png)

**Comment by Silabs-ArjanB** [comment]
Still needs merge from 40X

**Comment by silabs-oivind** [comment]
@silabs-mateilga . This is merged to e40s now. Please close ticket if you agree it's fixed.

**Comment by silabs-mateilga** [comment]
Fix works as intended, assert formally proven
