### ISSUE TITLE
Clarification of trigger register implementation for 0 triggers

### ISSUE THREAD

**Issue by silabs-halfdan** [openhwgroup/cv32e40s#419]
In the debug spec, implementing the trigger registers is optional if no triggers are implemented.
The reference manual does not clearly state whether or not the registers are implemented (with WARL(0x0)) when no triggers are implemented.

This can lead to misunderstandings.
One example is the ISS implementation of tcontrol, where the reference manual states the CSR is hardwired to 0 but does not state whether it exists for DBG_NUM_TRIGGERS==0. So for ISS it is always implemented and hardwired to 0 (addressed in separate issue).

**Comment by Silabs-ArjanB** [comment]
Hi @silabs-halfdan Doesn't the following clarify it good enough?

![image](https://user-images.githubusercontent.com/40633348/224716490-3a4c9929-c6cd-44e8-8d79-5e39e22f9627.png)

**Comment by silabs-halfdan** [comment]
@Silabs-ArjanB I also filed as an ISS bug. I guess this is explicit enough, as this did not seem to be the reason for the ISS implementation. Closing this ticket.
