### ISSUE TITLE
Unwarranted PMP Fault?

### ISSUE THREAD

**Issue by silabs-robin** [openhwgroup/cv32e40s#464]
### Component
**Component:RTL**: For issues in the RTL (e.g. for files in the rtl directory)

### Steps to Reproduce
1. My core-v-verif fork/branch: https://github.com/silabs-robin/core-v-verif/tree/pmprvfi_fix3
1. `668b73952c4186934165922614c862ff61de0473`
1. Run formal
1. Check `a_rvfi_mem_allowed_generalinstr` (Bound 14, `-engine_mode B`)

### Description
Two `rvfi_valid`s occur, the latter with a PMP fault exception.
But, investigating the signals show that the instr-side PMP check for both fetches seems fine.

![image](https://github.com/openhwgroup/cv32e40s/assets/75431602/1bac95a1-9482-4f08-92e5-5a36ce102871)

**Comment by silabs-robin** [comment]
@silabs-oivind ref discussion last Friday.

**Comment by silabs-oivind** [comment]
Hi,
This is a table jump, where the table jump instruction passes PMP checks, but the table jump target address fails PMP checks.
It seems like the design and RVFI behaves according to spec.

I'm not sure if you have enough information on rvfi to recognize and properly check this scenario. We might need to add some extra rvfi signals for this.

**Comment by silabs-robin** [comment]
Understood. I will update the assert accordingly, and request additional RVFI signals if needed.
Closing this issue as it seems the RTL/RVFI is doing the right thing.
