### ISSUE TITLE
Integrity bit is not forwarded to the alignment buffer

### ISSUE THREAD

**Issue by silabs-krdosvik** [openhwgroup/cv32e40s#473]
# Template for Bug Issue

## Forwarding of Integrity Bit

A clear and concise description of what the bug is:
OBI rew has integrity (see screenshot 1), but this is not registered in the alignment buffer (see screenshot 2)

What seems to be the problem:
The integrity bit is computed according to the core_tras_i.addr (see screenshot 3), but the core_tras_i.addr is connectred to the prefetcher_trans_addr (see screenshot 4), which dont correspond with the req address (see screenshot 5 and 6).

### Component

Indicate the component in which you found a problem (and we will add the appropriate label):
**Component:RTL**: cv32e40s core

### Steps to Reproduce
Please provide:
1. git hash: 29d44172
2. Command line: -
3. Logfile and/or wave-dump info (screen shots can be useful)
![image](https://github.com/openhwgroup/cv32e40s/assets/110398284/a07b84e8-12f0-4641-8078-85751fab8d31)
![image](https://github.com/openhwgroup/cv32e40s/assets/110398284/5793cfae-861a-42a6-a1bd-dc1b9180086a)
![image](https://github.com/openhwgroup/cv32e40s/assets/110398284/270cbbea-c421-4e28-854e-0f82a129bbcc)
![image](https://github.com/openhwgroup/cv32e40s/assets/110398284/6ebe04e8-3fa5-4d60-a456-69255ffcf4ee)
![image](https://github.com/openhwgroup/cv32e40s/assets/110398284/d01a10f4-2b74-4658-b2d6-39d2fc85be29)
![image](https://github.com/openhwgroup/cv32e40s/assets/110398284/e5d5f2dc-cc3b-4177-b9ca-1af11f793b43)

**Comment by silabs-oysteink** [comment]
Issue should be fixed with PR #474
