### ISSUE TITLE
Update to ratified version of Smepmp

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40s#74]
Update to ratified version of Smepmp

- Change version in intro.rst (if needed)
- Check for any spec changes compared to our earlier design target (0.9.1, https://docs.google.com/document/d/1Mh_aiHYxemL0umN3GTTw8vsbmzHZ_nxZXgjgOUzbvc8/edit#) and update User Manual, RTL and VPLAN
- Allow up to 64 PMP regions
- Treat RW(X) as WARL field (as already described in User Manual)
- Make PMP configuration reset values configurable via parameters

Some (but not all) of the above changes are already documented in the user manual via https://github.com/openhwgroup/cv32e40s/pull/78

**Comment by Silabs-ArjanB** [comment]
@silabs-oivind Has this been fixed now?

**Comment by silabs-oivind** [comment]
@Silabs-ArjanB. Yes, this is fixed.
